bookdown::gitbook:
  self_contained: false
  css: style.css
  df_print: "kable"
  number_sections: false
  config:
    toc:
      before: |
        <li><a href="./">Simulated Datasets With Binary Outcomes</a></li>
      after: |
        <li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>
bookdown::html_document2:
  code_folding: hide
  df_print: kable
  theme: flatly
  toc: yes
  toc_float: yes
  self_contained: true
  number_sections: false
